# Generated by Django 4.2.7 on 2023-11-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_curso_precio_curso_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='promocion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
