# Generated by Django 4.2.7 on 2023-11-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_curso_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=99.9, max_digits=6),
            preserve_default=False,
        ),
    ]
