# Generated by Django 4.2.7 on 2023-12-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_curso_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(upload_to='hero')),
            ],
        ),
    ]
